### ISSUE TITLE
What exactly is in `Allen1_cell_centroids.pkl` and how can I make my own?

### ISSUE THREAD

**Issue by cartal** [broadinstitute/Tangram#1]
Hi, 

I'm very eager to test your pipeline now using my Visium data. However, in your example notebook, there is this section:

```
'Load cells coordinates on Visium image'
cells_coordinates = mapping.utils.read_pickle('data/Allen1_cell_centroids.pkl')
```
The file `Allen1_cell_centroids.pkl` is not present in your `data` folder, and it is not clear how you can reproduce the file.

Could you please give an example on how to generate this file from the Space Ranger output?

Thanks

**Comment by lewlin** [comment]
Hi Cartal,

First: I updated all the links. Please pull from repo and find updated notebook and README file. The `Allen1_cell_centroids` file contains the centroids of each cell to be superimposed to the histological image. That is a result of out segmentation. You can download the file here:

https://storage.googleapis.com/tommaso-brain-data/tangram_demo/Allen-Visium_Allen1_cell_centroids.pkl

Please do not hesitate to ask more questions if I am not being clear.

**Comment by cartal** [comment]
Thanks for the quick reply! 

Ok, so I understand what is the file now. But then my question is, which is the equivalent file from a SpaceRanger run? And, do I need this file if I haven't done any segmentation? Could I bypass it? 

Many thanks

**Comment by lewlin** [comment]
The file contains the coordinates of each cells (center): to obtain that, the cells needs to be segmented in the histological image. To my knowledge, the file has no SpaceRanger analogue. A simple way to segment by yourself is to use the software ilastik (publicly available) on your H&E/Nissl stained image.

You cannot bypass this step if you want to deconvolve your Visium data using Tangram (because you need to tell the method how many cells are contained in each voxel). But you can circumvent this step if you simply want to perform a probabilistic mapping (for example, for correcting dropouts): in this case you can estimate the density "by eye" or use a public source such as the Blue Brain Cell Atlas (in our paper we treat both cases).

**Comment by cartal** [comment]
Thanks so much! This has been super useful!

**Comment by sokratiag** [comment]
Hi,

I would also like to test Tangram on Visium data (for deconvolution) but I am struggling a bit with extracting the cell centroids information from the histological image as you indicated. Did you use the 'voxel segmentation workflow' on ilastik? Would it be possible to share more info on how to extract this information? Thanks in advance!

**Comment by ravasthi-broad** [comment]
Hello Sokratia,
Thank you for your email. No, we did not use 'voxel segmentation workflow' but below is given the process how we calculated cell centroids for each voxel using the histological visium images.
To find cell centroids you can try "pixel classification" in Ilastik. Mark the cells as one label and background as another, I would suggest using the "live updates" feature while marking the labels and continuing the process of marking until you are satisfied with the results, then you may use "4. Prediction Export" with source set as "simple segmentation" to export your result as either an HDF5 or png file and read it using python as the file would be a matrix with 2/3 unique labels with one of the labels depicting cells. You may then convert it into a binary image and process it using "skimage" package to find cell_centroids.
You may find voxel centroids in the visium gene expression anndata file.
Below is the format for the cell_centroid pickle file.
column_1: x-coordinate of the centroid of the voxel - int
column_2: y-coordinate of the centroid of the voxel - int
column_3: number of cells detected in the voxel - int
column_4: list the centroids of cells in the voxel - int

**Comment by sokratiag** [comment]
Thanks a lot ravasthi that was really helpful.
