### ISSUE TITLE
No attribute 'pp_adatas' in tangram

### ISSUE THREAD

**Issue by ParitoshP702** [broadinstitute/Tangram#102]
I am trying to use tangram package to perform data imputation but when I try to use 'pp_adatas' function I simply receive the error stating : 

AttributeError: module 'tangram' has no attribute 'pp_adatas'

Is there any way to correct the issue?

**Comment by gaddamshreya1** [comment]
Hi @ParitoshP702, 

Thank you for your interest in Tangram! 
Now coming to the issue, I have a couple questions for you which will help me better understand how I can help you solve it:

1. How did you install tangram? I would recommend `pip install tangram-sc`.  Could you also check if you have **tangram** (**not tangram-sc**) package installed? In that case, I would uninstall that package as `pip uninstall tangram`.  

2. What version of tangram have you installed? you can check it this way: 
```
import tangram as tg
print(tg.__version__)
```

Let me know if 1. works for you! If not, I'll be to help further.

**Comment by Doomsday2021** [comment]
That worked for me , thnx a lot
