### ISSUE TITLE
Attribute error : module 'tangram' has no attribute 'map_cells_to_space'

### ISSUE THREAD

**Issue by Shikari666** [broadinstitute/Tangram#107]
Tangram package says ---------------------------------------------------------------------------
AttributeError Traceback (most recent call last)
in <cell line: 1>()
----> 1 ad_map = tg.map_cells_to_space(
2 adata_sc,
3 adata_st,
4 mode="constrained",
5 target_count=adata_st.obs.cell_count.sum(),

AttributeError: module 'tangram' has no attribute 'map_cells_to_space' when trying to run a example snippet code ad_map = tg.map_cells_to_space(
adata_sc,
adata_st,
mode="constrained",
target_count=adata_st.obs.cell_count.sum(),
density_prior=np.array(adata_st.obs.cell_count) / adata_st.obs.cell_count.sum(),
num_epochs=1000,
device="cpu",
)

**Comment by gaddamshreya1** [comment]
Hi @Shikari666, 

Thank you for you interest in Tangram! 
This is happening because you have the incorrect tangram package installed. Could you try the following: 
```
pip uninstall tangram 
pip install tangram-sc
```
I'm sure this will work. Otherwise please let me know! 
- Shreya

**Comment by Shikari666** [comment]
Thanks!

**Comment by 1liuchunlong** [comment]
![Image](https://github.com/user-attachments/assets/c3f15535-8427-4399-a3ef-c761e17e1d60)     It's stuck here and keeps running.
