### ISSUE TITLE
potential overfitting

### ISSUE THREAD

**Issue by jayypaul** [broadinstitute/Tangram#111]
Hi,

I'm wondering about how to properly select the number of epochs to run the algorithm. Should I run the algorithm once with default epochs, evaluate when the score appears to numerically stabilize, then re run it with a lower number of epochs and use that imputed information? I'm wondering if the team has utilized a more systematic framework for evaluating how to properly set the parameters of the algorithm, and avoid potential overfitting? Any thoughts and suggestions would be appreciated!

**Comment by jayypaul** [comment]
Additionally, I'm wondering if there's a mechanism already in place where the algorithm will choose the weights, etc corresponding to the number of epochs where the score has stabilized sufficiently during the training. From what I can tell I don't think so, but any thoughts on this also appreciated! 

Thanks!

**Comment by gaddamshreya1** [comment]
Hi @jayypaul, thank you for your interest in Tangram! 

We haven't evaluation the effect of the different number of training epochs in this version! However, its a good idea to see how much the mapping changes with different number of epochs by analyzing the cell annotation maps, diagnosis plots as well as AUC. 

@Hejin0701 do you have any other recommendations/suggestions?

**Comment by jayypaul** [comment]
Hey, thanks for your response, on this post and the other. I'll keep these ideas in mind.

Best Regards,

Jordan W.

**Comment by Hejin0701** [comment]
Hi @jayypaul Thanks for your interest in Tangram. Normally running large number of epochs does not cause the overfitting for Tangram. I have tested the Tangram mapping from 1E3 up to 1E5 epochs, the general cell type distribution stay pretty much the same. However, as Shreya mentioned, we do not have embedded tool to evaluate overfitting. One thing you can do if you are worried about overfitting is to run Tangram mapping at both cell (`mode='cells'`) and cluster (`mode=clusters`) level and then compare whether there are any significant difference between the two annotation maps. The cluster level mapping consists of much smaller parameters (~2 to 3 order of magnitude smaller) compared to cell level mapping and thus is much less prone to overfitting.

**Comment by jayypaul** [comment]
Hi Hejin, thanks for your insight and I appreciate the advice. Good to know that it's less of an issue than I thought!
