### ISSUE TITLE
Outdated seaborn dependency

### ISSUE THREAD

**Issue by Nick-Eagles** [broadinstitute/Tangram#15]
Hello,

This is a fairly small problem, but I figured it's still best to create an issue for it- in the most recent tutorial (`example/1_tutorial_tangram.ipynb`), the following function is called:

`tg.plot_training_scores(ad_map, bins=50, alpha=.5)`

This in turn seems to call `seaborn.histplot`, a function specific to seaborn>0.11.1, but the `environment.yml` file in this repository installs seaborn 0.10.1. When following through the tutorial in my own python file, I get the following error:

```
Traceback (most recent call last):
  File "/dcl02/lieber/ajaffe/SpatialTranscriptomics/LIBD/spython/tangram_testing/example_orig_nick.py", line 55, in <module>
    tg.plot_training_scores(ad_map, bins=50, alpha=.5)
  File "/users/neagles/.conda/envs/tangram/lib/python3.8/site-packages/tangram/plot_utils.py", line 26, in plot_training_scores
    sns.histplot(data=df, y='train_score', bins=10, ax=axs_f[0]);
AttributeError: module 'seaborn' has no attribute 'histplot'
```

Thus I believe `environment.yml` should be updated to require seaborn 0.11.1 instead of 0.10.1 (this fixed the issue for me).

Best,
-Nick

**Comment by ziqlu0722** [comment]
Hi Nick,

Thanks for pointing this out! We have updated the environment.yml on master. I'm closing this issue.

Best,
Ziqing
