### ISSUE TITLE
followup on squidpy integration

### ISSUE THREAD

**Issue by giovp** [broadinstitute/Tangram#26]
Hi @lewlin @ziqlu0722 @gscalia ,

following up on the chat re adding Tangram to Squidpy, I digged again into the repo and followed this tutorial: https://github.com/broadinstitute/Tangram/blob/master/example/1_tutorial_tangram.ipynb, here's my comments (in random order):
### `tg.pp_adatas`
Very useful function, but I was wondering if it would be possible to make everything happen `in place`, instead of copying over the anndata and reindexing? I'm thinking of something like this: https://github.com/YosefLab/scvi-tools/blob/b4256ebb84ebebd70fb920f73d13df9b9bbb73db/scvi/data/_anndata.py#L79
docs: https://docs.scvi-tools.org/en/stable/api/reference/scvi.data.setup_anndata.html#scvi.data.setup_anndata

It would boil down to finding a common set of markers from either the two adatas or an external list (as you show in the tutorial) and add it as a boolean series to the two adatas: `adata_[space, sc]["markers_tangram"]`. It would be straightforward for the `mapper` to subset and create the tensors afterward e.g. here: https://github.com/broadinstitute/Tangram/blob/909d70b04ec57b4edaf11bb55b7f44df6c6c227d/tangram/mapping_utils.py#L132
Of course this can happen in the squidpy call, so we could also work it out there in case you prefer current behavior. I think it would be desirable for memory req.

### `tg.map_cells_to_space`
Really cool that it accepts AnnData now! This makes it very convenient. There is a weird behaviour with the argument `d` (density?), which is set to `None` by default and is indeed exposed by the function, but is then re-set to either `None` or `np.ones(G.shape[0])/G.shape[0]` according to `mode`.

https://github.com/broadinstitute/Tangram/blob/909d70b04ec57b4edaf11bb55b7f44df6c6c227d/tangram/mapping_utils.py#L152

In our [tutorial]() we set it to `d = np.array(adata_st.obs.cell_count) / adata_st.obs.cell_count.sum()` since we show how to get segmentation masks counts (and coordinates for further plotting at the end) for each spot, with the image container. Is this a bug or the behaviour changed? Also, it's missing from the docstring

### `ut.project_cell_annotations`
https://github.com/broadinstitute/Tangram/blob/909d70b04ec57b4edaf11bb55b7f44df6c6c227d/tangram/utils.py#L114
we could save this output to `adata_space.obsm["[tangram/deconv]_results"]`. In case we have info on the number of cells per spot (e.g. after segmentation), would this still work out?
I remember in the previous tutorial there was an additional filtering step like this:
```python
# highest probability a cell i is filtered if F_i > 0.5'
filtered_voxels_to_types = [
    (j, adata_sc.obs.cell_subclass[k])
    for i, j, k in zip(F_out, resulting_voxels, range(len(adata_sc)))
    if i > 0.5
]
```
I guess such a filter could also follow `adata_map.X.T @ df`, and potentially make the matrix sparse?

Meanwhile, I'll open a PR on squidpy for starting the external module addition.

Happy to provide more feedback or contribute, let me know what you think!

best,
Giovanni

**Comment by ccruizm** [comment]
Good day!

I would like to know if there are any new developments on this! would be great to have the last version of Tangram working fully with Squidpy! it will be a great match!

Thanks!

**Comment by lewlin** [comment]
We have been working non-stop for the past 2 weeks :)
We'll release an update soon - hopefully next week.

**Comment by ccruizm** [comment]
Thanks for the update! looking forward
