### ISSUE TITLE
Example data missing?

### ISSUE THREAD

**Issue by HeesooSong** [broadinstitute/Tangram#28]
Hello,

I was trying out the Visium example, but couldn't find the marker gene data that is used to subset relevant markers.
The exact file that I think missing is "spacejams_visp_markers.pkl". It would be nice if you can put the download link as you did on snRNAseq data and others.

Best regards,
Heesoo

**Comment by gaddamshreya** [comment]
Hi Heesoo, 

Download link for 'visp_markers.pkl' is now included in the notebook.
