### ISSUE TITLE
About the coordinates 

### ISSUE THREAD

**Issue by MIAO803** [broadinstitute/Tangram#34]
Hi, thanks so much to provide the useful tool for a python user. 
I am going to use a sc-RNA data to annotate my 10X visum spatial transcriptomes data. I only have the coordinates for each spot, not the cells within the spot. Can I use this tool also ? From the exsample, I can see there is a pkl file which provides the cells number as well as the individual cell coordinates in the spot, which I don't have, or I can see from 10X visum platform, it's impossible to have those information.

**Comment by lewlin** [comment]
Yes you can use the tool without cell segmentation (you will be able to map and resolve cell types in space but you will not be able to deconvolve). 

@ziqlu0722 can you provide us with an example?

**Comment by MIAO803** [comment]
@lewlin 
Thanks for the reply!

**Comment by ziqlu0722** [comment]
Hi @MIAO803, please reference this [tutorial](https://github.com/broadinstitute/Tangram/blob/master/example/1_tutorial_tangram.ipynb) for mapping without cell segmentation. The data you need is your sc-RNA, your spatial transcriptomes data and a list of marker genes (In the example, the marker genes is computed following [scanpy tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html). 

I'm closing this based on comments above. Feel free to reopen if any further questions.
