### ISSUE TITLE
Follow up on Spot-Level Deconvolution

### ISSUE THREAD

**Issue by aseyedia** [broadinstitute/Tangram#36]
Hello,

My colleagues and I have been able to use Tangram to successfully map genes onto our Visium spatial dataset thanks to your incredibly helpful tutorial. However, we would like to implement deconvolution (i.e. assigning cell types to each spot of the Visium slide) as part of our Tangram pipeline in order to generate images similar to the one included in the manuscript and attached below for reference but we are unsure how to go about it. I was not able to find functions related to deconvolution in the Git repository with the exception of `df_to_cell_types` in utils.py:

https://github.com/broadinstitute/Tangram/blob/eb867f54c6e3a20872dbfc70bb7496f45d8a1dbe/tangram/utils.py#L376-L402

which is commented out. Is deconvolution forthcoming or am I overlooking something? 

![image](https://user-images.githubusercontent.com/43455034/124808634-290a5f00-df2d-11eb-8f66-d10c894b7e67.png)

Like I mentioned before, we have otherwise been able to implement some of Tangram’s functionality already and we appreciate the help you’ve given us in the past.

Thank you,
Arta Seyedian

**Comment by lewlin** [comment]
Woohoo - we love you enjoy the method.

We have not implemented yet deconvolution in "an easy" fashion BUT, the Squidpy team wrote a beautiful tutorial which I recommend

https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_tangram.html

Let me know if this helps (we are working on a simpler version but it will take some time)

**Comment by 3N4N** [comment]
@lewlin, in that tutorial for deconvolution, I cannot find the steps to get celltype proportions. Could you help me on that?

**Comment by lewlin** [comment]
Hi Enan,

I was responding on GitHub but I cannot see the message anymore: did you
delete it?

For the histogram of cell types: if you do deconvolutions (ie you know how
many cells you have in each spots), then computing an histogram of
frequencies is very simple. Did you mean you needed help on the
deconvolution instead?

Ciao
