### ISSUE TITLE
where to get Allen1_cell_count.h5ad dataset

### ISSUE THREAD

**Issue by vanhoan310** [broadinstitute/Tangram#4]
Dear Tommaso,

I want to run the mapping-visium-example.ipynb notebook. Currently I could not find where to get the Allen1_cell_count.h5ad dataset. Could you please tell me how to get the dataset?

Thanks!

**Comment by gscalia** [comment]
Hi,

the link for the dataset is in the README of the repo. You can download the dataset from here:

https://storage.googleapis.com/tommaso-brain-data/tangram_demo/Allen-Visium_Allen1_cell_count.h5ad
