### ISSUE TITLE
how to create Allen1_cell_centroids.pkl using my own Visium data 

### ISSUE THREAD

**Issue by caiquanyou** [broadinstitute/Tangram#5]
I want to use Tangram on my own data,but cannot find the way to create own cell_positon file like Allen1_cell_centroids.pkl?
how to create Allen1_cell_centroids.pkl using my own Visium data

**Comment by ravasthi-broad** [comment]
Hi,
Thank you for your question. The file "Allen1_cell_centroids.pkl" is a dictionary that holds the data of cell centroid coordinates. The process to calculate cell centroids for each voxel using the histological visium images is given below.

To find cell centroids over a histological image you can try "pixel classification" over software called Ilastik. Mark the cells as one label and background as another, I would suggest using the "live updates" feature while marking the labels and continuing the process of marking until you are satisfied with the results, then you may use "4. Prediction Export" with source set as "simple segmentation" to export your result as either an HDF5 or png file and read it using python as the file would be a matrix with 2 or 3 unique labels with one of the labels depicting cells. You may then convert it into a binary image and process it using "skimage" package to find cell_centroids.
You may find voxel centroids in the visium gene expression anndata file.
Below is the format for the cell_centroid pickle file.
column_1: x-coordinate of the centroid of the voxel - int
column_2: y-coordinate of the centroid of the voxel - int
column_3: number of cells detected in the voxel - int
column_4: list the centroids of cells in the voxel - int

I'll be happy to answer any further questions if you have any!  :)

**Comment by caiquanyou** [comment]
Thanks， that means I can generate this file if I already have the four columns data。

**Comment by ravasthi-broad** [comment]
Exactly! I have tried to describe a process of obtaining data for those 4 columns in my previous post. Let me know if that requires some more clarification.
