### ISSUE TITLE
module 'tangram' has no attribute 'pp_adatas'

### ISSUE THREAD

**Issue by NingWang1729** [broadinstitute/Tangram#50]
For some reason, there does not appear to be the pp_adatas function anymore.
<img width="685" alt="module 'tangram' has no attribute 'pp_adatas'" src="https://user-images.githubusercontent.com/63263298/149064929-48ebf8dd-7406-40d6-8655-18dc7781a85d.png">

**Comment by lewlin** [comment]
@ziqlu0722 could you please look into this?

**Comment by ziqlu0722** [comment]
Hi @NingWang1729! Could I know how did you install tangram and what version do you use?

**Comment by NingWang1729** [comment]
Hi @ziqlu0722!

I used !pip install tangram-sc on the collab tutorial, and pip install tangram-sc on a linux machine.
The tangram version on the linux environment is version 1.0.2

**Comment by ziqlu0722** [comment]
Hi @NingWang1729, I cannot explain how I missed your reply! Actually it doesn't complain about missing `pp_adatas` function when I try it on google colab or on my linux machine. I close this for now but feel free to reopen it if you still have issue. Thank you!

**Comment by gebdu** [comment]
>>> tg.pp_adatas(adata_sc, adata_st, genes=markers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tangram' has no attribute 'pp_adatas'

tangram version 1.04; installed:        pip install tangram-sc

**Comment by Dondonn** [comment]
Did you maybe also pip installed tangram (and tangram-sc)?
If this is the case you can try: pip uninstall tangram.

**Comment by ParitoshP702** [comment]
Even I am facing the same issue,  tangram does not seem to have 'pp_adatas' function .

Is there any way to correct the issue?

**Comment by NingWang1729** [comment]
The original issue I encountered was due to a file named `tangram.py` being present and imported rather than the tangram library. Hope this helps.
