### ISSUE TITLE
question about save figures to pdf

### ISSUE THREAD

**Issue by Lena926** [broadinstitute/Tangram#53]
Your idea is very interesting. And thanks to your useful tutorial link, I've got my result by processing my scRNA-seq data. But cause I use R in my daily work , I'm unfamiliar about how to save the image to PDF after tg.plot_cell_annotation_sc. Hope you could give me a hand.

Thanks a lot!

**Comment by gaddamshreya** [comment]
Hi @Lena926, Thank you for using Tangram! 
Here's some python code that will help you save the plot from _tg.plot_cell_annotation_sc_ in pdf format:
```
fig, axs = plt.subplots(nrows=3, ncols=3, figsize=(10,10))
for ann,a in zip(annotation_list, axs.flat):
    tg.plot_cell_annotation_sc(ad_sp, [ann], spot_size=50, ax=a)
plt.tight_layout()
fig.savefig('annotation_plot.pdf')
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
you can change the number of figures in each row and column using _nrows_ and _ncols_ respectively and size of the figures using _figsize_. 

Let me know if this works for you! 

-Shreya

**Comment by Lena926** [comment]
Hi Shreya, 

I successfully saved the plot as pdf format with the code you gave.

Thanks for your help!!!

-Lena

**Comment by gaddamshreya** [comment]
completed
