### ISSUE TITLE
Incorrect scale factor used by default

### ISSUE THREAD

**Issue by Nick-Eagles** [broadinstitute/Tangram#56]
Hello,

I've noticed a mismatch between histology pixel coordinates and spots (spatial coordinates) when using the `tg.plot_cell_annotation_sc` function, which went away when I manually supplied the `scale_factor` argument. If I understand correctly, when `adata_st.uns['spatial']` exists, the idea is to use that information, which should include scale factor, to accurately overlap the histology and spatial coords. In particular, my spatial AnnData had the scale factor stored in `adata_st.uns['spatial'][sample_name]['scalefactors']['tissue_hires_scalef']`, which I believe is a standard location where it should be found (rather than needing to specify `scale_factor` explicitly).

I traced the source of the "mismatch" to the [default assignment of scale factor as 0.1](https://github.com/broadinstitute/Tangram/blob/5eb4ca1566d849de614c8036382689eab5181534/tangram/plot_utils.py#L181), which is [passed to `sc.pl.spatial`](https://github.com/broadinstitute/Tangram/blob/5eb4ca1566d849de614c8036382689eab5181534/tangram/plot_utils.py#L206-L208) even when `adata_st.uns['spatial']` exists. I imagine the default of 0.1 only makes sense when `adata_st.uns['spatial']` doesn't exist.

I believe the same issue exists for the `tg.plot_genes_sc` function, though I haven't explicitly checked this. Apologies if I'm misunderstanding, and I've stored the scale factor in a non-standard location. Note that I'm using tangram 1.0.2 as installed through pip, and am following along the squidpy tutorial.

Thanks for providing the Tangram software!

Best,

-Nick

**Comment by lewlin** [comment]
@gaddamshreya Could you also look at this please?

**Comment by gaddamshreya** [comment]
@Nick-Eagles thank you for identifying this issue!

**Comment by gaddamshreya** [comment]
@Nick-Eagles I've removed scale factor's default value for the plotting functions and updated the tutorial; thank you for bringing this to our attention!

**Comment by Nick-Eagles** [comment]
Great! I appreciate you looking into this.
