### ISSUE TITLE
Question about citation of dataset

### ISSUE THREAD

**Issue by EronHou** [broadinstitute/Tangram#59]
Hello.

I've read your tutorial about tangram via the link https://github.com/broadinstitute/Tangram/blob/master/tutorial_tangram_without_squidpy.ipynb. This link contains a snRNA-seq dataset and a slide-seq2 dataset collected from MOp area in adult mouse brain. I want to use this dataset for further scientific research but this website doesn't provide a clear citation.  I am wondering whether you could provide the data source or published paper to help me. 

Thanks for your help.

**Comment by lewlin** [comment]
You can reference PMID 33288904. 

Ciao

**Comment by EronHou** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        Thanks for your help. I understand~
        Yimin Hou
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Tommaso ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/4/2022 00:07
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [broadinstitute/Tangram] Question about citation of dataset (Issue #59)
        
      
    
  
  
You can reference PMID 33288904.
Ciao
