### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by simonmfr** [broadinstitute/Tangram#60]
Hi, I assume the following section in your [tutorial ](https://github.com/broadinstitute/Tangram/blob/master/tutorial_tangram_with_squidpy.ipynb) should rather say 'spatial data' than 'scRNAseq'? At least that's what I see in my data.

`Some genes are detected with very different levels of sparsity - typically they are much more sparse in the scRNAseq than in the spatial data. This is due to the fact that technologies like Visium are more prone to technical dropouts.`

**Comment by gaddamshreya** [comment]
typos fixed
