### ISSUE TITLE
conda package conflict

### ISSUE THREAD

**Issue by jonathanperrie** [broadinstitute/Tangram#61]
Hello,

I have cloned the repo and am running:

`conda env create -f environment.yml`

But I get this error: 
![error](https://i.imgur.com/oRRjzUp.png)

Not sure what to do besides install things one at a time.

**Comment by gaddamshreya** [comment]
hi @jonathanperrie I couldn't reproduce the error. However, I suspect this issue is related to your conda base environment rather than Tangram. Could you let me know the python version in your conda base environment?
