### ISSUE TITLE
plot_cell_annotation_sc not found

### ISSUE THREAD

**Issue by kguion1** [broadinstitute/Tangram#62]
I've been using your package to deconvolute some visium data following the tutorial. I have successfully made it to the ad_map creation. However, when I try to plot I receive the below error and it looks like it can't find the function. Any help is appreciated!

`AttributeError: module 'tangram' has no attribute 'plot_cell_annotation_sc' `

**Comment by gaddamshreya** [comment]
Hi @kguion1 May I know the version of tangram you are using?

**Comment by kguion1** [comment]
tangram-sc                0.4.0                    pypi_0    pypi

**Comment by gaddamshreya** [comment]
@kguion1 the current version of Tangram is 1.0.3 and all the tutorials work best with this version of Tangram. 
The 'plot_cell_annotation_sc' is a new function added in the recent versions. Thank you for using Tangram!

**Comment by kguion1** [comment]
okay! I was using the 0.4.0 because of the link to this yaml so might be worth updating: https://github.com/scverse/squidpy_notebooks/blob/main/envs/tangram_environment.yml in one of the tutorials. 

Thanks so much for your help :)

**Comment by kguion1** [comment]
Hi, after updating to the new version, now it cannot find the `pp_adatas` function. My tangram-sc package is version 1.0.3
