### ISSUE TITLE
General Questions: Visium

### ISSUE THREAD

**Issue by kguion1** [broadinstitute/Tangram#63]
I am attempting to use your tool for visium data and was hoping to clarify my analysis pipeline with your great tool. I currently am using publicly available single cell data, but will eventually have matched single cell data for the visium sample. I would ideally like to map the matched single cell data onto the visium spatial slide. From reading your tutorial, it seems that this would have to be done in two steps: deconvolution of the visium spatial spots and then mapping of the single cell data onto the slide. It was unclear from the tutorial if tangram is the appropriate method to be using for both these steps and which functions I should be using. Here are my questions:

1. Is this two step assumption: (1) deconvolution using cell types determined by single cell clustering. (2) single cell mapping. correct? or can you jump directly to mapping of the single cells onto the visium spots?
2. If tangram is not the appropriate method for the deconvolution (or the analysis I am describing), is there another method that you suggest that I can then utilize the output in the single cell mapping capabilities of tangram?
3. Is there a tutorial on performing this analysis on Visium data specifically?

As I have never done this type of analysis before, any guidance would be appreciated. 

Thank you so much for your time.

**Comment by gaddamshreya** [comment]
Hi @kguion1 
You can directly map single cell data onto a visium slide without the need for deconvolution. In this case, the assignment of cell types in space with be probabilistic. You can follow this [tutorial](https://github.com/broadinstitute/Tangram/blob/master/tutorial_tangram_without_squidpy.ipynb) which is a general tutorial for mapping single cell of most technologies onto spatial data of most technologies. 

You can use the above tutorial as long as your spatial data is in anndata format. In case of visium, you can use this [scanpy function](https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_visium.html) to read a visium package into anndata.
