### ISSUE TITLE
project_genes input inconsistency?

### ISSUE THREAD

**Issue by kguion1** [broadinstitute/Tangram#64]
I was trying to run the project_genes and got an error that my .obs indices were not equal. I looked through the documentation was confused which inputs the project_genes takes: the single cell adata or the spatial adata? In the code the argument name `adata_sc` implies that it should be single cell, but the argument descriptions states spatial. 

To follow up, what should the obs.index be representing in these adata inputs?

def project_genes(adata_map, adata_sc, cluster_label=None, scale=True):
    """
    Transfer gene expression from the single cell onto space.
    Args:
        adata_map (AnnData): single cell data
        adata_sp (AnnData): gene spatial data
        cluster_label (AnnData): Optional. Should be consistent with the 'cluster_label' argument passed to `map_cells_to_space` function.
        scale (bool): Optional. Should be consistent with the 'scale' argument passed to `map_cells_to_space` function.
    Returns:
        AnnData: spot-by-gene AnnData containing spatial gene expression from the single cell data.
    """

**Comment by gaddamshreya** [comment]
Hi @kguion1!

project_genes takes single cell data as the second argument i.e., adata_sc. 
And, thank you for bringing the documentation typo to our attention! 
Let me know if you still have the obs lengths.

**Comment by kguion1** [comment]
okay!

the issue resolved when I specified cluster_label!
