### ISSUE TITLE
missing areas in plot_cell_annotation_sc

### ISSUE THREAD

**Issue by kguion1** [broadinstitute/Tangram#65]
Hi!

After running the `map_cells_to_space` and `plot_cell_annotation_sc`, I noticed that a lot of my spots ended up dropping out and the plot results in large areas missing. Is this to be expected? 

![image](https://user-images.githubusercontent.com/42556019/176736449-3f12e3ae-857d-4d04-859d-a3c4b1948b60.png)

**Comment by gaddamshreya** [comment]
Hi @kguion1!
I wouldn't expect loss of spots because of mapping. 
Could you tell me the dimensions of the spatial data before mapping and the dimensions of **ad_map**, which is the result of mapping?

**Comment by kguion1** [comment]
my bad! found the error :) thanks!

**Comment by vicmuck** [comment]
What was the error that you found? I am running into a similar issue. When I run the tutorial from [here](https://github.com/broadinstitute/Tangram/blob/master/tutorial_tangram_with_squidpy.ipynb), the final picture the dots are off in the picture (shown below) and I am not sure why.

<img width="1019" alt="Screen Shot 2022-10-25 at 9 45 17 PM" src="https://user-images.githubusercontent.com/98892221/197915108-1d084420-6203-4592-8024-811dbd071ee1.png">
