### ISSUE TITLE
 the coordinates are flipped

### ISSUE THREAD

**Issue by Lena926** [broadinstitute/Tangram#70]
Hello, thank you for creating such a useful tool, I am very happy to use it in my data, but when I draw a graph with tg.plot_cell_annotation_sc, I find that the coordinates are flipped, how can I solve it?

when I use scanpy I got this:
![image](https://user-images.githubusercontent.com/61967854/183295628-64cff455-7cb5-45de-82ae-7de2ce593e28.png)

But tg.plot_cell_annotation_sc
![image](https://user-images.githubusercontent.com/61967854/183295702-194267c5-6e85-46ea-8ed4-55f630099815.png)

Thanks a lot!

**Comment by giovp** [comment]
Hi @Lena926 ,

the reason for the inconsistency is that in scanpy (or [squidpy](https://squidpy.readthedocs.io/en/latest/api/squidpy.pl.spatial_scatter.html) ) we enforce the origin (0, 0) to be on the top left, as is common convention with image data. You can recover this by flipping the coords in `adata.obsm["spatial"]` with `np.flipud` and `np.fliplr`

**Comment by Lena926** [comment]
> Hi @Lena926 ,
> 
> the reason for the inconsistency is that in scanpy (or [squidpy](https://squidpy.readthedocs.io/en/latest/api/squidpy.pl.spatial_scatter.html) ) we enforce the origin (0, 0) to be on the top left, as is common convention with image data. You can recover this by flipping the coords in `adata.obsm["spatial"]` with `np.flipud` and `np.fliplr`

Thanks for your help, I'll give it a try
