### ISSUE TITLE
Add b/w plotting option to tg.plot_genes_sc()

### ISSUE THREAD

**Issue by simonmfr** [broadinstitute/Tangram#72]
It would be super useful if you could add an option to `tg.plot_genes_sc()` and `tg.plot_cell_annotation_sc()` so that the tissue image is shown in black and white. The pink colour of HE stains tends to blur the spot colours. Also, an option to change the alpha of tissue images and spots would be appreciated. Scanpy has similar options for `sc.pl.spatial(visium, color="total_counts", bw=True, alpha_img=0.8)`. Thanks!

**Comment by gaddamshreya** [comment]
Thank you for this suggestion! I've updated the plotting functions accordingly

**Comment by simonmfr** [comment]
Works perfectly, thanks
