### ISSUE TITLE
count_cell_annotations doesn't work with specific column values

### ISSUE THREAD

**Issue by witchhead** [broadinstitute/Tangram#78]
I have been working on my personal data set following the tutorial given by tangram on deconvolution.
All the code till count_cell_annotations seems to work all good and issue no problem.
However, when choosing the specific annotation for count_cell_annotations, the system returns this error.
ad_map, adata_sc, and adata_st were all formatted based on the tangram tutorial and had been working for all the processes.

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_36176/1374048480.py in <module>
----> 1 tg.count_cell_annotations(
      2     ad_map,
      3     adata_sc,
      4     adata_st,
      5     annotation="our_annotation",

~\anaconda3\lib\site-packages\tangram\utils.py in count_cell_annotations(adata_map, adata_sc, adata_sp, annotation, threshold)
    281 
    282     for k, v in vox_ct:
--> 283         df_vox_cells.iloc[k, df_vox_cells.columns.get_loc(v)] += 1
    284 
    285     adata_sp.obsm["tangram_ct_count"] = df_vox_cells

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3359             casted_key = self._maybe_cast_indexer(key)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
   3363                 raise KeyError(key) from err

~\anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

~\anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

**Comment by gaddamshreya** [comment]
Hi @witchhead, 

The argument 'annotation' in the function _tg.count_cell_annotations_ is a string which should be the name of the column containing cell type annotations in the obs dataframe in adata_sc. 
Will you be able to confirm that a column names "our_annotation" exists in the obs dataframe of your single cell data ? 
If not, then adding the list of your annotations to the adata_sc.obs["our_annotation"] will eliminate the error. 

Please let me know if it works for you!

-Shreya

**Comment by witchhead** [comment]
So, the annotation was a column that we have been working on for the whole sequence and had no problems before this function. I have made sure the column is contained in adata_sc but it still seems to return an error.

TypeError: 'AAACCTGAGCTCAACT-1-0       EN-V1
AAACCTGAGGAATGGA-1-0      IN-STR
AAACCTGAGTCGCCGT-1-0     IPC-nEN
AAACCTGAGTCTCCTC-1-0    RG-early
AAACCTGAGTGCCATT-1-0     IPC-nEN
                          ...   
TTTGTCATCGCAAACT-1-3     IPC-nEN
TTTGTCATCGTAGATC-1-3         vRG
TTTGTCATCGTAGGAG-1-3    RG-early
TTTGTCATCTAACTTC-1-3     IPC-nEN
TTTGTCATCTTGCCGT-1-3    RG-early
Name: nowakowski_med, Length: 45214, dtype: category
Categories (28, object): ['Astrocyte', 'Choroid', 'EN-PFC', 'EN-V1', ..., 'nIN', 'oRG', 'tRG', 'vRG']' is an invalid key

**Comment by cynthier** [comment]
> 

Hi, I encountered the same problem, have you solved it?

**Comment by gaddamshreya** [comment]
Hi @witchhead and @cynthier, I was unable to reproduce this error and I'm working towards finding the solution.
Meanwhile, can you let me know the version of tangram you're using?

**Comment by cynthier** [comment]
> Hi @witchhead and @cynthier, I was unable to reproduce this error and I'm working towards finding the solution. Meanwhile, can you let me know the version of tangram you're using?


Thank you for your attention, the information from conda list command is shown below.

# Name                    Version                   Build  Channel
tangram-sc                1.0.3                    pypi_0    pypi

**Comment by gaddamshreya** [comment]
Hi @witchhead and @cynthier, 

Thank you for your patience. I was able to reproduce this error when mapping using cells or cluster modes! In the tutorial, the mode used was constrained and the function executed completely. 
In the latest version 1.0.4, this bug was fixed. Please check that out and let me know if you run into any other problem. 
Thanks again for bringing this to my attention. 

-Shreya

**Comment by cynthier** [comment]
Thank you for your work and your attention. It works now.
