### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by boyiguo1** [broadinstitute/Tangram#80]
In Section https://github.com/broadinstitute/Tangram#how-to-run-tangram-at-cell-level, it says

> This allows to extend gene throughput, or correct for dropouts, if the single cells have higher quality (or more genes) than **single cell data**.

Do you mean _spatial data_ instead of **single cell data**?

**Comment by gaddamshreya** [comment]
yes! Thanks for catching that!
