### ISSUE TITLE
Best practices on 500k+ cells

### ISSUE THREAD

**Issue by quentinblampey** [broadinstitute/Tangram#88]
Hello,

Thanks for the great package. I find Tangram very fast when using GPUs, but very memory hungry for a large number of cells (which is expected, since the cell pairwise matrix becomes huge).

I have about 500k cells per image, and what I am currently doing is the following: I randomly split all the cells into 10 bags of ~50k cells, then I run Tangram on each bag of cells.

This process is very fast and not memory hungry, but I was wondering if you believe this is a good practice? If not, do you have any advice?
Indeed, the annotations may be inconsistent from one bag to another, even though in practice it seems quite stable. To smoothen the predictions after concatenating the bags annotations, I was considering running leiden clustering (with high resolution) and assigning all cells of a given cluster to the most frequent cell type. But maybe there is a better and cleaner solution.

Thanks!

**Comment by lewlin** [comment]
Ciao Quentin,

What you are doing is good Tangram practice - at least this is what we do too when we used the method on large sections. Indeed, checking stability of annotations is important and sometimes we bootstrap cells and repeat mapping to estimate uncertainty.

Hope it helps.

**Comment by quentinblampey** [comment]
Hello @lewlin, thanks for the answer, It's good to know that you are doing something similar.
And good idea to bootstrap cells and repeat the process to improve the stability, I will try that out!
