### ISSUE TITLE
deterministic cell-typing of spatial data.

### ISSUE THREAD

**Issue by CJChen1010** [broadinstitute/Tangram#90]
Hello, 

I am interested in using Tangram to do cell-typing of my lab-developed spatial transcriptomics data with snRNA-seq reference of human primary motor cortex. Since we do segmentation based on nuclear staining, each voxel in our spatial data represent single cell. So, I run Tangram with. density_prior='uniform'. There is 28,841 cells in my spatial data and 38,034 cells in my snRNA-seq data (24 cell types). Here is exactly how I run Tangram. The probabilistic cell-typing looks correct. Those L2/3, L4, L5, L6 excitatory neurons localize correctly in laminar structures. 
![image](https://github.com/broadinstitute/Tangram/assets/96495403/fb6cc0bb-71e9-4a7c-90c7-2ec2623c0f1b)

However, when I take the cell type label with highest probability in 'tangram_ct_pred' table to deterministically assign the cell type label. Here is the output.
<img width="951" alt="Screen Shot 2023-05-16 at 2 29 17 PM" src="https://github.com/broadinstitute/Tangram/assets/96495403/51664d9a-74e3-4c2a-9d59-8887115500aa">

The deterministic cell-typing result looks wrong. Those laminar structures of excitatory neurons disappear and the percentage of each cell type is off. Besides, I notice if I sum the probability of each cell type across each row (each cell), the probability doesn't sum up to 1. If I sum all values in the 'tangram_ct_pred' table, the value is equal to the number of cell type in my snRNA-seq data. If I run Tangram in the 'cells' mode the values in the table sum up to the number of cells (38,034) in my snRNA-seq data instead of the number of cells in my spatial data (28,841). So, I wonder how to do the deterministic cell-typing correctly with Tangram so that those 28,841 cells in my spatial data are aligned with the highest probabilistic cells in snRNA-seq data.

**Comment by caiquanyou** [comment]
I am also confused about how to deterministic mapping using the result ad_map?

**Comment by tsvvas** [comment]
Hi @CJChen1010 and @caiquanyou!

The `plot_cell_annotation` function maps probabilities of cell types onto spatial coordinates, whereas `plot_cell_annotation_sc` behaves in a more deterministic way. To obtain cell type predictions tangram normalizes probabilities in the `construct_obs_plot` function.

While I am not a developer of tangram, I [came up with a workaround](https://github.com/broadinstitute/Tangram/issues/96#issuecomment-1680458390), how to obtain deterministic assignment, inspired by that hidden function.

Hope that helps,
Vasily
